### ISSUE TITLE
Message-parts are not aligned in columns

### ISSUE THREAD

**Issue by Hoolean** [korobi/Korobi#1]
Log messages are not aligned in columns. Usually, the standard is to right-justify nicks in their own column and to left-justify the messages in a following column, to allow for the best readability and flow of conversation.

**Comment by lol768** [comment]
Thanks to @bendem, we have http://codepen.io/anon/pen/pvKqqy to work with on this.

**Comment by bendem** [comment]
If you need any help styling stuff, ~~I'm the men~~ let me know. :wink:

**Comment by lol768** [comment]
:heart:
