### ISSUE TITLE
Latest Log Lacks Lines, Actions Are Adversely Absent

### ISSUE THREAD

**Issue by mbax** [korobi/Korobi#100]
Example latest log:

> 16:16:08   mbaxter brb
> 16:17:00   mbaxter Get in your last pettings now

Corresponding full log:

> 16:16:08   mbaxter brb
> 16:16:10   \*   mbaxter pets ^o^
> 16:16:10   \*   ^o^ purrs and cuddles
> 16:16:18   \*   kenzierocks pets ^o^
> 16:17:00   mbaxter Get in your last pettings now

**Comment by kashike** [comment]
Seems fine to me? https://korobi.io/network/esper/channel/kitteh.org/logs/#L148-153

**Comment by octylFractal** [comment]
I see actions in the log @kashike linked.

**Comment by kashike** [comment]
:dancer:

**Comment by Zarthus** [comment]
```
(18:31:05) <+kashike> hi mbaxter 
(18:39:02) <+Zarthus> I think he means https://korobi.io/network/esper/channel/kitteh.org/
(18:39:06) <+Zarthus> "Latest logs"
(18:39:09) * +Zarthus hi
(18:39:17) <+Zarthus> yeah, there's no actions there
```

**Comment by octylFractal** [comment]
Snapshot of above log from the link in the log: ![image](https://i.imgur.com/2RF0nOv.png)

**Comment by kashike** [comment]
~~Not a bug, so unless this is a feature request it is invalid~~

**Comment by mbax** [comment]
Joins,parts,quits,etc. are less important, but cutting out `/me` eliminates part of the conversation. Why is this not a bug?
