### ISSUE TITLE
Line selection is lacking

### ISSUE THREAD

**Issue by Hoolean** [korobi/Korobi#12]
Currently, the following changes are needed to line selection:
- The ability to deselect by clicking again
- The ability to select ranges my holding down the Shift modifier key [(see Issue#4)](https://github.com/korobi/Korobi/issues/4)

**Comment by lol768** [comment]
The behaviour has changed in the following ways:
- Adding individual lines has been changed to use the `Ctrl` key modifier
- A new check has been added for when the `Shift` modifier key is being held down. This highlights a range of lines based on whichever line you had last selected
- Clicking on a sole line _which is already highlighted when no other lines are highlighted_ without any modifier keys being pressed will result in the line being deselected. For deselecting individual lines whilst retaining the rest of the selection, the `Ctrl` modifier should be used.

It is hoped this behaviour feels natural to use.
