### ISSUE TITLE
Prepend command with pipe to notice

### ISSUE THREAD

**Issue by lol768** [korobi/Korobi#13]
Also:

~~.cmd @username~~

~~Should print "username: <cmdtext>" to chat~~

~~.cmd @@username~~

~~Should print "username: <cmdtext>" as notice to command sender and username.~~

Document .cmd username@[@]

**Comment by kashike** [comment]
This has been done (https://github.com/korobi/Freya/commit/2c3af691902922d951b70daa7d763d773a0abf92, https://github.com/korobi/Freya/commit/74f67efe4ba3f46230138d85cf831cdd03068739), but using different prefixes (as suggested by @Zarthus). Will be deployed later on.
