### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by lol768** [korobi/Korobi#21]

**Comment by lol768** [comment]
I think we can do this with a mango query.

**Comment by kashike** [comment]
"I think we can do this with a mango query."
Possibly, although K/ES is quite nice too.

**Comment by lol768** [comment]
if you have the RAM :P

**Comment by bendem** [comment]
Kinda related to #31

**Comment by lol768** [comment]
We have indexes now on message, actor_name & actor_hostname!

**Comment by anna-is-cute** [comment]
indices*

**Comment by lol768** [comment]
http://online.wsj.com/mdc/public/page/2_3022-intlstkidx.html

**Comment by bendem** [comment]
Search should be available from everywhere on the site and provide quick access to networks and channels.
Basic mockup on desktop would look like the image below; while the mobile interface would go fullscreen.
![](https://i.imgur.com/R3OHRIU.png)

Focusing the search box would send an ajax request to get the possible channels (maybe be cached in session/localStorage) and suggest a search for channel, network, or text (If the user starts their search with a `#`, the suggestions will only contain channels).

If the user selects a suggestion, they gets redirected to the corresponding page. If they selects one of the 3 generic suggestions, they gets redirected to the search module with results matching their choice and preselected search options.

The simple search module would look like the image below (types are above the search field to be easily accessible while suggestions are displayed - this mockup looks horrible, I know, but that's not the point).
![](http://i.imgur.com/VYwwX2H.png)

An advanced mode should be available with checkboxes for the fields to search in (nick, hostname, actions, messages) and any other option we can think of.

EDIT: Advanced mode phrasing

**Comment by bendem** [comment]
#60 needs to be done first

**Comment by jamierocks** [comment]
Sphinx has the capability to search as well... Would we have separate search or unified search? - I recommend unified although it may be tricker to set up.

**Comment by lol768** [comment]
heh, I didn't consider docs searching - I presume that's what Sphinx can do?

**Comment by jamierocks** [comment]
Yes Sphinx can do search - see sponges docs as a demo

**Comment by lol768** [comment]
We can have an option for a docs search perhaps:

![](http://i.imgur.com/jWNouM5.png)

Probably docs search should be at the bottom, though.

**Comment by jamierocks** [comment]
Yes - that would be nice
