### ISSUE TITLE
[CRITICAL] IRC messages aren't properly escaped with the new parsing code

### ISSUE THREAD

**Issue by lol768** [korobi/Korobi#28]
**Update (15-03-2015)**: This regressed, see https://github.com/korobi/Korobi/issues/28#issuecomment-80768589 but has been patched in such a way that breaks links. Preferable to allowing arbitrary HTML content IMO.

HTML tags in IRC messages are blindly passed to the view on staging without being escaped in any way. This allows users to inject arbitrary HTML into the page by sending HTML to a logged channel. CSP isn't properly enabled on staging to allow the profiler to work which makes this even worse.

This does not affect production for obvious reasons.

**Comment by bendem** [comment]
Should be fixed by https://github.com/korobi/Web/compare/5abb82987fd083ac4549bb6045fe4ba225735541...1263fa464243def3514bb065ff5714f6ac3dc514

**Comment by lol768** [comment]
This was found to still be a problem and subsequently patched in https://github.com/korobi/Web/commit/b20263ecbef5ad8cd1dcd2a31305356790beacae. Unfortunately this patch also breaks linking. This didn't directly hurt visitors using modern browsers due to the CSP we have set up but it's still a cause for concern.

We need a better way of ensuring that this doesn't continue to be an issue so I'm leaving this open until we can test it properly. It's worth noting that the original test we had for this **continued to pass even when this was still an issue** which is worrying. I'd suggest making something functional that does a real request in order to better prevent regressions of this. Unfortunately, the ChannelController is going to need a refactor to make it testable in this way (we need to stop using repositories directly and start dependency injecting them - we also should make controllers POPOs so we can instantiate them in the test and pass in a mock/stub object).

**Comment by kashike** [comment]
@bendem

**Comment by bendem** [comment]
That is fixed and shouldn't happen ever again.
I have no idea how to setup a nicer test that the one we currently have tho.

**Comment by kashike** [comment]
Closing for now.
