### ISSUE TITLE
What do we want to see before the next deploy to prod?

### ISSUE THREAD

**Issue by lol768** [korobi/Korobi#29]
#9 #10 #2 are things I'd like done. Ultimately it'd be nice to see a rapid cycle of "work, tets on staging, deploy to production once done".

@bendem @Kashike

**Comment by kashike** [comment]
I'd like for the channel overview page to be sane, it's a mess right now

**Comment by bendem** [comment]
I've mainly been looking for bugs to fix. The new parser was kind of a mess :-)
Else then that, I'd like to see #32 in the next production push.

**Comment by kashike** [comment]
I'm going to close this, we've done hundreds of deploys since this was made.
