### ISSUE TITLE
Raw log

### ISSUE THREAD

**Issue by Hoolean** [korobi/Korobi#3]
There should be an option to view the 'raw' log, in plain text. This allows for easy downloading/scraping/low-bandwidth/lightweight viewing of logs.

**Comment by lol768** [comment]
Would JSON be an appropriate compromise?

**Comment by kashike** [comment]
@jamierocks

**Comment by jamierocks** [comment]
@kashike ?

**Comment by kashike** [comment]
I totally didn't poke the wrong person. Sorry, jamie

**Comment by jamierocks** [comment]
lol, it's ok :P

**Comment by lol768** [comment]
@Hoolean

**Comment by bendem** [comment]
Json looks like this for now (subject to changes)

``` json
[{
    "id":"54fbb71ae4b0a83e3220f51d",
    "timestamp":"02:42:34",
    "role":"operator",
    "nickColour":"12",
    "nick":"Kashike",
    "message":"notice: .&gt;&gt;meow user1,user2"
},{
    "id":"54fbb71ae4b0a83e3220f51e",
    "timestamp":"02:42:34",
    "role":"operator",
    "nickColour":"12",
    "nick":"Kashike",
    "message":"self: .&lt;meow"
},{
    "id":"54fbb71be4b0a83e3220f51f",
    "timestamp":"02:42:35",
    "role":"operator",
    "nickColour":"12",
    "nick":"Kashike",
    "message":"<a href=\"http:\/\/i.kitteh.club\/MmIzZ\" target=\"_blank\">http:\/\/i.kitteh.club\/MmIzZ<\/a>"
},{
    "id":"54fbb8f6e4b0a83e3220f56a",
    "timestamp":"02:50:30",
    "role":"operator",
    "nickColour":"12",
    "nick":"Kashike",
    "message":"and lol768: ff can&#039;t load gmail"
}]
```

**Comment by lol768** [comment]
@Hoolean

**Comment by Hoolean** [comment]
Personally, I'd like to see raw text as well as JSON. I'd be happy to write a view that converts the JSON into various IRC log formats if I find the time. :)

**Comment by Hoolean** [comment]
See the possible code here -->

**Comment by jamierocks** [comment]
I quite like @bendem's JSON view, however a text file might also be nice to have.

**Comment by bendem** [comment]
With the last changes, I think we could encode into multiple formats based on the content-type request header.
What do you think would be a good text/plain format? Would it be better if the messages were parsed and htmlified, unchanged or stripped from format chars?

**Comment by lol768** [comment]
To me plaintext would have no formatting characters, no HTML etc.
