### ISSUE TITLE
Instead of wrapping names, cut them off at max length.

### ISSUE THREAD

**Issue by Zarthus** [korobi/Korobi#30]
Weechat has an extra last character sized slot for nick-cut offs.  

```
21:01:24               pdle │ a                                                                           
21:01:27 the_australian_wha+│ a                                                                           
```

This would be neat for Web as well, I imagine.

**Comment by bendem** [comment]
Could work with text-overflow, but I'm not sure how the `display: table-cell` will like being `max-width`'d

**Comment by lol768** [comment]
@bendem Can't we truncate it server-side? Or do you want this to be dependent on the screen width?

**Comment by bendem** [comment]
Since the width of the logs is responsive, I'm not sure we can identify a maximum length to target when truncating.
