### ISSUE TITLE
Highlight all things ?nick=Zarthus (or #L1,L5,...) said 

### ISSUE THREAD

**Issue by Zarthus** [korobi/Korobi#31]
With the current line highlighting, by clicking on a name you _could_ make it so that all things the nick has said get highlighted.

I'm not sure how well it will work out, but I think the idea might be nice to consider.

**Comment by lol768** [comment]
Neat concept

**Comment by lol768** [comment]
I've added a `data-nick` attribute to the `<div>` elements for this.
