### ISSUE TITLE
Toggle message types.

### ISSUE THREAD

**Issue by Zarthus** [korobi/Korobi#32]
- [x] Basic join/part message toggling
- [ ] Advanced toggling for each message type

**Comment by bendem** [comment]
That's totally needed

**Comment by lol768** [comment]
@bendem Something I'd like to see is giving lines more 'semantic' classes/data attributes, e.g. the `event-user-quit` class below:

``` html
<div class="line js-hl event-user-quit" data-line-num="4">
    <span class="timestamp">
        21:34:42
    </span>
    <span class="nick irc--04-df ">&lt;--</span>
    <span class="message">zack6849 (zack6849) has quit (Ping timeout: 378 seconds)</span>
</div>
```

**Comment by bendem** [comment]
Storing `$chat->getType()` [here](https://github.com/korobi/Web/blob/master/src/Korobi/WebBundle/Controller/ChannelController.php#L257) would make that available to the view and the json/tail.

**Comment by lol768** [comment]
Sounds like a plan

**Comment by bendem** [comment]
I added `data-event-type` and `data-event-id` to each line.
The rest is adding a button toggle triggering some js, but I'm not sure of where to put it.

``` js
$('.line').each(function(i, v) {
    if(['join', 'quit'].indexOf($(v).attr('data-event-type')) != -1) {
        $(v).hide();
    }
});
// or
$('.line').each(function(i, v) {
    $(v).show();
});
```

The button could be added next to the tail button (see #2)

**Comment by lol768** [comment]
> The button could be added next to the tail button (see #2)

Yeah, we need some sort of secondary nav button group or similar across the top. Still working on the SASS code for that but we have buttons now.

**Comment by bendem** [comment]
I was thinking, maybe an openable thing with checkboxes for all the message types (not only join/part) would be neat.

**Comment by Zarthus** [comment]
That's nice, but what events would you make hidable in there? i don't think it needs to be openable if it is just quit, join, part (and maybe privmsg). Are there other events that need hiding?

**Comment by bendem** [comment]
You could hide all the message types: join, part, quit, message, action, topic, nick, mode, kick (could be useful if you're not actually looking for a message but a kick, a mode, a topic change or such things).

**Comment by lol768** [comment]
Sounds neat for advanced users, but I'd suggest some simple buttons with sane defaults for users who just want to filter out the most common cruft

**Comment by bendem** [comment]
Basic toggle part/join is implemented in staging

**Comment by lol768** [comment]
:+1:
