### ISSUE TITLE
Hide lines by pressing a 'X' at the very right side of the UI

### ISSUE THREAD

**Issue by Zarthus** [korobi/Korobi#33]
Sometimes you want to take a screenshot, or copy a piece of text. But there's something blocking the way! 

By having a 'hide this line' button this shall no longer be the problem.

(might collide a bit with the highlighting, but one would be local only (removing lines being per-refresh), and the other would be for sharing with others (in-url))

**Comment by lol768** [comment]
I suggest we only show this when hovering over the line to minimise clutter and repetition.

**Comment by Zarthus** [comment]
I was thinking outside of the message box actually, and yes, only when you hover close to it.

**Comment by bendem** [comment]
```
<+Zarthus> @bendem: picking up lines and dragging them around with a trash can in the top rihgt?
<+Zarthus> or 'remove all unhighlighted lines'
<+Zarthus> only appearing when something is highlight
...
<@bendem> it'd be touch, I'd have long touch provide the option
<@bendem> but it's not
<+Zarthus> can you make a options menu appear when doubleclicking on the line?
<+Zarthus> or when you drag it to the left
<+Zarthus> similar to how mobile devices do 
<+Zarthus> like delete/highlight line/copy i dunnmo
<@bendem> that'd be interesting to see
```
