### ISSUE TITLE
Investigate new stats system

### ISSUE THREAD

**Issue by lol768** [korobi/Korobi#34]
https://github.com/influxdb/influxdb-java

http://influxdb.com/docs/v0.8/introduction/getting_started.html

**Comment by lol768** [comment]
@Kashike I've had a look at InfluxDB and I'm really liking the look of it so far. Can you let me know if it will work for us in terms of support from Freya and whether you can install it on the server?

I suggest we do hourly or daily stats generation runs simply because it gives us the ability to spend more time doing interesting maths because we don't have to serve a quick http response. Maybe a cron script would work?

In terms of the actual maths and stats involved we can do a variety of things. When I was playing InfluxDB I was storing stats as objects like the following:

``` json
{"total": 12, "ops": 2, " voices": 8, "other": 2}
```

This is simplistic (ignores half ops etc) but should give you an idea of the sort of data Influx wants to see. The server automatically associates the data with a time and sequence number - all Freya needs to do is use the client lib to pass the server the data.

The neat we can do is use the aggregate functions which Influx supports. For example, if we consider the number of ops and voices as discrete random variables we can work out the covariance between them and subsequently the product moment correlation coefficient. If the PMCC is close to 1 it suggests the number of ops and voiced users in a channel is positively correlated. Additionally, we can work out values such as the standard deviation of the total number of ops to see how the numbers of users fluctuates. By analysing a larger period of time, we can determine the derivative of the number of users over time and determine if the channel in question appears to be growing or declining. A lot of this can be done for messages too - Freya could record the length of each message, the number of words in it etc and then do similar analysis. We could JOIN the two data sets - do the number of words in each message go down in bigger channels (e.g. in #bukkit are answers/messages of a lower quality compared to a smaller channel like #drtshock)?

It might be interesting to model channel joins with a poisson distribution which would allow us to predict the probability of a user joining in a given time period for a channel. This could be applied to different channels and even whole networks to see a wider trend by comparing the value of lambda for a given set period of time.

I'm sure you get the picture that there's a ton we can do with regard to this on top of the usual pretty (but boring) graphs that we can use to replace pisg.

**Comment by kashike** [comment]
@lol768 https://github.com/influxdb/influxdb-java - Let me know if that will work for what would need to be submitted from Freya

**Comment by lol768** [comment]
@Kashike Yup! Might want to do it asynchronously if possible just to avoid slowing down the bot (or does PircBotX work like that anyway?)

**Comment by lol768** [comment]
> It might be interesting to model channel joins with a poisson distribution which would allow us to predict the probability of a user joining in a given time period for a channel. This could be applied to different channels and even whole networks to see a wider trend by comparing the value of lambda for a given set period of time.

We're conveniently ignoring the fact that events aren't independent when netsplits happen or BNC services die :wink:

**Comment by Zarthus** [comment]
See https://stats.quakenet.org for inspiration.

**Comment by kashike** [comment]
https://github.com/korobi/Web/issues/125
https://github.com/korobi/Felix/issues/7
https://github.com/korobi/Internal/issues/25
