### ISSUE TITLE
Flash highlighted messages on page load

### ISSUE THREAD

**Issue by lol768** [korobi/Korobi#35]
à la StackExchange sites (but reversed):

http://programmers.stackexchange.com/questions/159637/what-is-the-mars-curiosity-rovers-software-built-in/159638#159638

Maybe also a smooth animated scroll down to them?

**Comment by Zarthus** [comment]
I strongly dislike smooth-animation scrolls (especially if they take too long) and prefer immediate-starts-at (Like how SO does it)

**Comment by lol768** [comment]
> I strongly dislike smooth-animation scrolls (especially if they take too long)

Yeah, to be fair the smooth scrolling is probably more of a gimmick and/or annoyance than anything useful.

**Comment by bendem** [comment]
What about message ranges? If the selection fades out, you can't see what was selected after the animation.
And just making the selection blink sounds kinda sparkles to me.

Not that I'm against it, just that I don't really see the point of it.

**Comment by lol768** [comment]
> @bendem said:
> What about message ranges? If the selection fades out, you can't see what was selected after the animation.

---

> @lol768 said:
> à la StackExchange sites (**but reversed**): :stuck_out_tongue: 

Fading out after would be silly, yes. Making it 'pulse' or 'flash' (see https://daneden.github.io/animate.css/ for my inspiration) would serve the purpose of making it clear what has been highlighted.

Multiple message ranges are an issue. I can only suggest we apply this animation to the first range we encounter (and only scroll to the centre of the page for that range too).

> Not that I'm against it, just that I don't really see the point of it.

This is inspired by an interaction I had [yesterday](https://dev.korobi.io/esper/bukkit/logs#L13-14). Users who are less experienced with IRC, reading etc are likely to not realise what's going on unless the message is flashed for them.
