### ISSUE TITLE
Add messaging feature

### ISSUE THREAD

**Issue by nathyong** [korobi/Korobi#36]
It would be convenient to send messages to offline users using a command such as `.msg` or `.tell`, perhaps with the following syntax:

```
.msg korobi did you hear about the latest macbook?
```

The message could then be delivered to korobi using a hilight or a query when the user is online again -- either when they have logged back in or when they have sent a message.

**Comment by Zarthus** [comment]
You have MemoServ for this, I don't think this is a task that Korobi should do (and a lot of third party bots already implement this, I very rarely see it used properly).

**Comment by lol768** [comment]
> You have MemoServ for this

This assumes the user has a NickServ account.
