### ISSUE TITLE
No padding at bottom of logs

### ISSUE THREAD

**Issue by lol768** [korobi/Korobi#38]
Mind looking at this? I know you'd previously done stuff with this before

**Comment by lol768** [comment]
@Kashike Can you reproduce this one? Not sure I can anymore :o

**Comment by bendem** [comment]
I set a margin at the end of main fixing that for logs and also every other pages using main as central element in https://github.com/korobi/Web/commit/4af9d8ec46ef973bea63672511f95ff38af8b2ad

**Comment by lol768** [comment]
Yeah, I can only assume I had the CSS cached or something
