### ISSUE TITLE
Shift-clicking the brush does not select a range of lines

### ISSUE THREAD

**Issue by Hoolean** [korobi/Korobi#4]
It is common practise in UIs to allow for shift-clicking line-numbers with the mouse to select a range of lines. Instead, multiple lines are selected; this behaviour should be bound to a different modifier-key and the range-selection behaviour should be used with shift.

**Comment by Hoolean** [comment]
Merged into [Issue#12](https://github.com/korobi/Korobi/issues/12)

**Comment by lol768** [comment]
Suggest closing this.
