### ISSUE TITLE
Voice-only notices

### ISSUE THREAD

**Issue by anna-is-cute** [korobi/Korobi#40]
```
[15:07:46]  <+jkcclemens>   also, this https://korobi.io/esper/hawkfalcon/logs
[15:07:51]  <+jkcclemens>   those are voice-only notices
[15:07:54]  <+jkcclemens>   why are they in the log
```

**Comment by Zarthus** [comment]
agreed, vnotices and higher should not be logged. (unless we can make a system where only voices in the channel can see them)

**Comment by anna-is-cute** [comment]
It would have to be so voices could only see notices from when they actually had voice in the channel, too. If someone is devoiced, a vnotice happens, then they're revoiced, they can just check the logs and see what they didn't see unless further precautions are taken.

Easier to just exempt them.

**Comment by kashike** [comment]
Should be fixed in https://github.com/korobi/Freya/commit/9029378dd5fe644d5850ca2a96153cbb7d65b196. Web needs to be updated to reflect changes.

**Comment by lol768** [comment]
Closing this now since Web has been updated. Cheers @jkcclemens for reporting this and @kashike  for fixing. Surprised it wasn't noticed earlier.
