### ISSUE TITLE
Permission add button doesn't work

### ISSUE THREAD

**Issue by matthewprenger** [korobi/Korobi#45]
The permission `add` button on the channel admin page of [korobi.io](https://korobi.io) doesn't do anything anymore. A new permission line is not created.
http://puu.sh/gGaBU/a43b0e5d8f.jpg

**Comment by lol768** [comment]
Works fine in staging. @Kashike Can you reproduce this in staging?

**Comment by kashike** [comment]
Forgot to close this last night.
