### ISSUE TITLE
 Parameter "channel" for route "channel" must match "[^/]++" ("" given) to generate a corresponding URL. 

### ISSUE THREAD

**Issue by lol768** [korobi/Korobi#46]
Network pages don't seem to load at all. I can only repro this for EsperNet - Rizon works fine.
A GET to /esper on staging gives the InvalidParameterException with message in the title. Makes me think there's an invalid channel in the config or something (not sure this is strictly a web issue, but it should still be better handled regardless)..

**Comment by kashike** [comment]
Fixed in https://github.com/korobi/Web/commit/13ce83f435f47361217482bc08e2b5a6b629bbc3.
