### ISSUE TITLE
As a user I'd like to see logs in my own timezone so that I know when events occurred. 

### ISSUE THREAD

**Issue by turt2live** [korobi/Korobi#48]
This can be done either by reading the browser's timezone or by having the user specify a timezone (more intrusive).

**Comment by bendem** [comment]
[korobi/Web@`5a1aa69...a986579`](https://github.com/korobi/Web/compare/5a1aa692939abc89db145bfd3eedf174ca68727e...a986579e8eb1374e3c863beda41c39ecbff8758b?w=1) implements that behavior.
Would an option to see logs in another timezone be wanted (if so, it'll wait for #9 with the others)?

**Comment by lol768** [comment]
This is going to be problematic. If we translate times client-side with JS (which I believe @bendem has done):
- The server will request the day's logs. The server will assume the day starts at 00:00 **UTC** which would mean that logs would break into a new day at odd times depending on the user's timezone
- This means you might only ever see local times which are offset, e.g. no events before 02:00 local time will be displayed because they are part of the previous day
- What happens with daylight savings?

If we set a cookie with the timezone and use that on the server to lookup each day:
- Permalinks which highlight specific lines will break
- Links to log pages for a specific day will be different for each client
  - Possible fix, remove the year/month/day route and have the route require two unix timestamps instead. Then we can have some JS which generates the URLs when users click on calendar days.

**Comment by turt2live** [comment]
Might I suggest something like this workflow:
1. User visits log page (`/channel/logs/[day]`)
2. JavaScript detects timezone and requests logs (`AJAX to /somewhere?timezone=...`)
3. Server gets the specified day of logs
4. JavaScript appends a timezone parameter to the URL (URL is now `/channel/logs/[day]?timezone=...`, for example)
5. User can now share the link safely while still highlighting log lines

This would mean that the JavaScript would not use the browser timezone if the timezone is specified in the URL and that users can communicate activities without fighting weird logic. 

As a bonus, however, if the user who receives the shared link (the link with `?timezone=...`) has a different timezone then the JavaScript/server could convert the log scope to their timezone, ensuring any selected lines are correctly accommodated for. A "secret" `?force=true` parameter could be added to disable this functionality if desired (advanced users may want to do this).

**Comment by lol768** [comment]
We can do items 1, 2 and 3 (though this will require an extra HTTP request to grab the logs). This will mean JS is required for viewing logs so maybe a fallback route would also be a good idea.

@bendem will know more about this than me, but I think we can use the [history API](https://developer.mozilla.org/en-US/docs/Web/Guide/API/DOM/Manipulating_the_browser_history#Adding_and_modifying_history_entries) to change the URL and add the timezone parameter (item 4).

I looked into daylight savings and `new Date().getTimezoneOffset();` will account for that. An issue I can see is that existing links to particular lines don't have the timezone parameter in them and thus will be broken. Not sure we can do a lot about that unless we can somehow detect legacy URLs (maybe change the route for the new log viewer approach).

I can foresee issues with highlighted lines and automated timezone conversion. A highlighted line at 00:30:36 won't be in a day's logs for someone in UTC-1. We'll need to somehow accommodate this - I was thinking "Oh, we can just grab the previous day's logs" but that won't work if one line from one day is highlighted and another is highlighted from another day. Alternatively, we could dump the logs from both days onto the page and give them appropriate titles etc.

**Comment by bendem** [comment]
I implemented local timezone toggling in https://github.com/korobi/Web/compare/41a07fdef5364fc3063e7399e5e5a03a05ae9111...3a5961c14ff48a14fdac342bba0258e3f4dbe62f.

Do you really want all that complex stuff you're talking about? I mean, I don't think anybody will really be bothered if the log doesn't start at midnight.

**Comment by lol768** [comment]
It's highlighting that'll be problematic though, bendem. I'm less bothered about when the logs start.

**Comment by bendem** [comment]
Well, the user can currently choose to view the logs in their local timezone or UTC (which is the goal of this issue), only the timestamps change.
So the only problem would be that the logs start at midnight UTC which can be different for each timezone.

**Comment by lol768** [comment]
@bendem Yeah, which would mean links to particular lines no longer correlate and users sharing links to particular lines generate URLs which only work for those in the same timezone (unless I'm missing something?)

Maybe we should disable highlighting when the local timezone option is selected?

**Comment by bendem** [comment]
Links are based on their position on the page, not on timestamps.
So if I link to `#1-2`, you'll see the first 2 lines highlighted, with the timestamps of your local timezone (or UTC if not active). And I'll see the same 2 lines highlighted, but with the timestamps of my local timezone (or UTC if not active).

**Comment by bendem** [comment]
```
@bendem | lol768, except if someone complains about it, I'd keep it that way. If someone complains, I guess we'll have to scratch our brains really hard
@lol768 | yeah, that seems like a fair enough compromise for now
```

**Comment by lol768** [comment]
Guess we'd better reopen this ref #97
