### ISSUE TITLE
Timestamp padding

### ISSUE THREAD

**Issue by Zarthus** [korobi/Korobi#49]
The padding-right on timestamps makes for an awkward small region of the logs that is still clickable (and will highlight your logs), even when you don't intend to.

![Timestamps](http://i.imgur.com/L7FWFBs.png)

**Comment by lol768** [comment]
Split this one into two issues, see #51 for the right-click highlighting. The padding issue seems like more of a CSS thing, whereas we'll do the right-click checking in JS.

**Comment by Zarthus** [comment]
you 'atta boy!

**Comment by bendem** [comment]
https://github.com/korobi/Web/commit/277bf72015a2d4280d3c99dfa03ad249d1e656ad

**Comment by bendem** [comment]
I can't css, ignore me

**Comment by lol768** [comment]
/me gives @bendem a gold star for trying

**Comment by bendem** [comment]
:+1:
