### ISSUE TITLE
No link to archives

### ISSUE THREAD

**Issue by lol768** [korobi/Korobi#5]
Was considering a calendar format

**Comment by lol768** [comment]
Also depends on #9

**Comment by lol768** [comment]
decided on a navbar - button group structure

**Comment by kashike** [comment]
poke @lol768

**Comment by lol768** [comment]
Can we get staging working again to allow for this to be more easily tested before deployment to production?

**Comment by kashike** [comment]
https://github.com/korobi/Web/commit/c7454db9789cc8d69328e1e327c5722cb9789b35
https://github.com/korobi/Web/commit/a2a5f268e2f6922e51a07380df6cc660ff095fa0
