### ISSUE TITLE
Rightclick shouldn't highlight lines

### ISSUE THREAD

**Issue by lol768** [korobi/Korobi#51]
Issue split from #49:

**@Zarthus said:**

> I also don't believe timestamps should highlight messages on right clicking, in cases of you wanting to copy the text or whatever.

**Comment by Zarthus** [comment]
:+1:

**Comment by bendem** [comment]
https://github.com/korobi/Web/commit/277bf72015a2d4280d3c99dfa03ad249d1e656ad
