### ISSUE TITLE
Docs should use monospace font rather than italics for command syntaxes and help strings

### ISSUE THREAD

**Issue by Zarthus** [korobi/Korobi#62]
for example: https://docs.korobi.io/channel/commands/removing.html

**Usage:** _.<delcmd|unsetcmd> [-i <index>] <name>_

Should be:

**Usage:** `.<delcmd|unsetcmd> [-i <index>] <name>`

And

so to remove the first value of the hit command you could use _.delcmd -i 0 hit_.

Could similarily become:

so to remove the first value of the hit command you could use `.delcmd -i 0 hit`.

**Comment by jamierocks** [comment]
This seems to be an issue with Sphinx as it uses < cite> and not < code>. I will speak about this in IRC as we can change the style from <code>code {</code> -> <code>cite {</code>. this would fix the problem, but preferably we want to see if we can get sphinx to use < code> in the first place.

**Comment by bendem** [comment]
as I said, semantic. From the [spec](http://www.w3.org/TR/html-markup/cite.html): _"The cite element represents the cited title of a work; for example, the title of a book mentioned within the main text flow of a document."_

**Comment by jamierocks** [comment]
It's understandable from the above description why it is using < cite>. We wouldn't be going too far of it's definition by using it.

**Comment by lol768** [comment]
I'm not sure how you got to that conclusion :/

<cite> is not for quotes per the [standard](https://html.spec.whatwg.org/multipage/semantics.html#the-cite-element), it's explicitly for the cited title of a work. Example:

``` html
<p>The <cite>HTML Living Standard</cite> describes how to use HTML elements correctly.</p>
```

`.<delcmd|unsetcmd> [-i <index>] <name>` is not the _title_ of a work. Nor is it a reference to a particular work. It's just some usage information.

Why's it matter, you might ask? We can just style it with CSS and nobody will care!

The meaning of the tag is important for accessibility - people using screenreaders and other assistive technologies. These sorts of software might decide to treat citations differently. Search engines might decide to treat the content inside the tags as references to other works.

**Comment by jamierocks** [comment]
Eh, I will try get this done ASAP.

**Comment by jamierocks** [comment]
The thing is - Sphinx has these cool things called code-blocks... the issue is it kind of requires a language.

My guess would be 'bash' if it is supported.

**Comment by bendem** [comment]
[Doc](http://sphinx-doc.org/markup/code.html) seems to say you can use `none` tho

**Comment by jamierocks** [comment]
Well there we go :D

**Comment by jamierocks** [comment]
Will fix tomorrow - going to sleep soon

**Comment by lol768** [comment]
bendem to the rescue!

**Comment by lol768** [comment]
Any updates on this one @jamierocks?

**Comment by jamierocks** [comment]
@lol768 I will start working on this now :D

**Comment by lol768** [comment]
Great!

**Comment by lol768** [comment]
@jamierocks is this fixed? Can this be closed?

**Comment by bendem** [comment]
OK, it seems like the solution would be to use `.. code-block:: none` instead of `.. code::` for code blocks. Then styling `.highlight pre` a bit and all should go along nicely.
