### ISSUE TITLE
Decrease load times on large log files.

### ISSUE THREAD

**Issue by Zarthus** [korobi/Korobi#63]
When a log file is above 1,000 lines, truncate it to 500 logs. As the user scrolls down, automatically fetch another row of 500 lines, etc.

This would have to be trickily implemented when highlights are being linked, seeing as you can have more than one line highlight.

**Comment by bendem** [comment]
Having logs populated with ajax by default would degrade the experience of users with js disabled devices

**Comment by Zarthus** [comment]
You could paginate it for when JS is disabled, having a 'go to next set of logs' generating the logs 500 to 1000, etc. When the JS detects you're near the bottom, it'll remove the 'go to next set' and instead grabs it via ajax.

If an active channel has ~3000+ logs, it's a sure way to freeze a browser for at least several seconds. An even more active channel (which is totally possible over the course of a day) could do far worse.

**Comment by lol768** [comment]
Have you got a link to a particularly slow logs page?

**Comment by Zarthus** [comment]
Anything with a buttload of logs. it's the entire process of receiving the data and loading the css that makes it take so long.

I know https://korobi.io/esper/FTB/logs/2015/06/13 is rather active commonly, but anything that just has a load of content will be slow due to how much you send. The page I just linked took me roughly 10 seconds to load with caching disabled.

**Comment by bendem** [comment]
I'm pretty sure the size of the html has nothing to do with it. I'll try and see where is the bottleneck (I'd say it's either the log parsing server-side or a badly optimized js)

**Comment by Zarthus** [comment]
it's both server and client side. The more html/css/js you have to process the slower your page will load. pages with less logs definitely load faster.

Loading a text file in a text editor with 10,000 lines is significantly slower than loading one with 1,000.

**Comment by bendem** [comment]
I removed the js looping through each line of log, that should be a bit better. The rest needs optimization server side

**Comment by kashike** [comment]
I believe this has been resolved. @bendem

**Comment by bendem** [comment]
The only bottleneck left is the datepicker, but I think it's ok to keep it that way
