### ISSUE TITLE
korobi/Web#25 Display notice message when date has no logs

### ISSUE THREAD

**Issue by kashike** [korobi/Korobi#69]
https://github.com/korobi/Web/issues/25

**Comment by bendem** [comment]
https://github.com/korobi/Web/commit/ffb2ff11881b1642ca3ec60554e4ad4d613ca54b

**Comment by lol768** [comment]
@bendem Should we still send a 200 OK for these scenarios?

**Comment by bendem** [comment]
The only way to access these pages would be by typing the url or consulting the logs of the day. In both case, I don't think there is a need for that.

**Comment by lol768** [comment]
My worry is someone sending a link to a page with no logs and it somehow getting indexed.

**Comment by bendem** [comment]
Should probably send 404 if the date is not provided then.

**Comment by bendem** [comment]
https://github.com/korobi/Web/commit/a989152307b578b57984e425ab6cd4cd2ff2299f

**Comment by lol768** [comment]
Seems to work, https://dev.korobi.io/esper/korobi/logs/2016/06/19/
