### ISSUE TITLE
Remove light theme

### ISSUE THREAD

**Issue by lol768** [korobi/Korobi#73]
I'm not convinced anyone uses the light theme. A lot of the components look terrible when using it and logs are unreadable.

Anyone have a problem with it being removed?

**Comment by bendem** [comment]
:+1: \o/

**Comment by lol768** [comment]
@Kashike @Zarthus @evilmidget38 might have thoughts on this

**Comment by jamierocks** [comment]
No docs support anyway, often looks horrid.

**Comment by natemort** [comment]
I kind of like the look of the light theme, but I'll agree that in its current state it's nonfunctional, and if no one else really wants to maintain it, then it might as well be removed.
