### ISSUE TITLE
Stats information exceeds bounds of browser window

### ISSUE THREAD

**Issue by Hoolean** [korobi/Korobi#83]
Opera 30.0.1835.59
Arch Linux

The stats, which appears to attempt to be centred, instead is too wide; this has the effect that - combined with the padding - it overflows.

![Piccy](https://i.imgur.com/8zghRFg.png)

**Comment by lol768** [comment]
@kashike Thoughts on making this along with #84 and #85 depend on #34? Is there much point working on the pisg implementation?

**Comment by Zarthus** [comment]
I do believe that was the idea. @lol768

**Comment by kashike** [comment]
@lol768 That is the idea, yes.
