### ISSUE TITLE
Check NS account status in #factions before auto message 

### ISSUE THREAD

**Issue by lol768** [korobi/Korobi#86]
Logged in users can probably be ignored.

Suggestion from Techcable. Should use WHOX, assuming mbaxter has support for it.

**Comment by mbax** [comment]
WHOX support is nearly ready for use. Just need to properly handle users, as previously they had been immutable internally as well as via snapshots and now they're definitely not.

**Comment by mbax** [comment]
Actually, from my brief testing I think it's pretty much ready to go. 0.2.8-SNAPSHOT will have it and after stronger testing that'll be released within a week.

**Comment by lol768** [comment]
Great to hear!

**Comment by mbax** [comment]
Relevant commits:
https://github.com/KittehOrg/KittehIRCClientLib/commit/114ead0dc4277ec7b2000faf28d05871ccded1f3
https://github.com/KittehOrg/KittehIRCClientLib/commit/afda9479024a443a7527547db05b6425d4597adc
https://github.com/KittehOrg/KittehIRCClientLib/commit/af8d9c9fb4f5898db69cdbc8a3f71918ae0da982
https://github.com/KittehOrg/KittehIRCClientLib/commit/97ddba6ff9516ffd090335629a6172444b47250c
https://github.com/KittehOrg/KittehIRCClientLib/commit/97020595746fb3a0db1fcc2b48ab505d93c22c1a

Checking User#getAccount() should provide accurate information on networks utilizing extended-join, account-notify, and WHOX.

**Comment by mbax** [comment]
![any day now](http://i3.kym-cdn.com/photos/images/facebook/000/592/253/714.jpg)

**Comment by kashike** [comment]
![tada](http://i.imgur.com/08SqfHD.jpg)

**Comment by mbax** [comment]
And there was much rejoicing

![yay](http://i.imgur.com/MKQIS73.gif)
