### ISSUE TITLE
New UI Components: Labels, buttons, breadcrumbs and alerts

### ISSUE THREAD

**Issue by lol768** [korobi/Korobi#9]
https://korobi.io/style-guide
- [ ] labels
- [ ] buttons
- [ ] breadcrumbs
- [ ] alerts

**Comment by bendem** [comment]
Would a floating button be the solution for all the log options we don't know where to place?
I'm thinking of something like the floating button from material design displaying multiple buttons when hovered.
The multiple buttons could be a tail button, a calendar button opening a date picker, a button to hide join/part messages and a button for advanced filtering opening a side panel

Floating button
![](https://i.imgur.com/UGEHjJX.png)

Date picker
![](http://i.imgur.com/0RGcZGv.png)

**Comment by lol768** [comment]
My concern is http://www.webpagesthatsuck.com/mysterymeatnavigation.html

**Comment by bendem** [comment]
> My concern is http://www.webpagesthatsuck.com/mysterymeatnavigation.html

I don't think there is currently another way to integrate new features to the log view than a floating/fixed buttons. Putting buttons on the top or the bottom of the page would involve heavy scrolling for channels with large activity.

**Comment by lol768** [comment]
What about users with screens <= 68em in width? There's not really any space for the floating sidebar nav. I agree with the scrolling issue, too but it might be worth thinking about how often the buttons are actually going to be used. Are you likely to need to keep going back and forth from the logs to the buttons?

**Comment by bendem** [comment]
> What about users with screens <= 68em in width? There's not really any space for the floating sidebar nav.

Floating icons are especially good for smaller screens actually (that's the reason it works so well for android designs).

> it might be worth thinking about how often the buttons are actually going to be used. Are you likely to need to keep going back and forth from the logs to the buttons?

That's a good point. Would it make sense to have all these options on top and a _back to top_ button instead?

**Comment by lol768** [comment]
That could work. @lDucks added a floating "back to top" button on a project we worked on once.
