### ISSUE TITLE
Allow visiting /channel/requesting without .html extension for docs.korobi.io

### ISSUE THREAD

**Issue by Zarthus** [korobi/Korobi#91]

**Comment by jamierocks** [comment]
Was this discussed?

**Comment by Zarthus** [comment]
If it is possible, yes.

The main website already strips extensions due to its router.

**Comment by kashike** [comment]
@jamierocks

**Comment by jamierocks** [comment]
I was looking into this last night :P I didn't find anything related to it on their website, so I will take a look through the config.

Else there is a way we can strip the extensions, just it isn't as nice.

**Comment by Zarthus** [comment]
I don't think it's a biggie, if gratimax's new docs prove to work nicely it's better if our attentions are focused there.

**Comment by jamierocks** [comment]
I totally agree with you, however it would be nice to get this done as the rest of the site follows that standard.
