### ISSUE TITLE
Add light theme

### ISSUE THREAD

**Issue by kashike** [korobi/Korobi#92]
referencing https://github.com/korobi/Web/issues/85

**Comment by jamierocks** [comment]
Ideally we would use javascript to switch, so it works with the docs.

**Comment by Zarthus** [comment]
I had the idea of placing two small buttons in the bottom right to switch themes, yeah.

Should be possible with 

```
<link href="light.css" rel="alternate stylesheet" title="Light theme">
```

But I've never tried it out. 

https://developer.mozilla.org/en-US/docs/Web/CSS/Alternative_style_sheets

**Comment by jamierocks** [comment]
That would be cool.
